// This file was generated by Mendix Studio Pro.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
// Special characters, e.g., é, ö, à, etc. are supported in comments.

package myfirstmodule.actions;

import com.mendix.core.objectmanagement.DataValidationInfo;
import com.mendix.systemwideinterfaces.core.IContext;
import com.mendix.webui.CustomJavaAction;
import com.mendix.systemwideinterfaces.core.IMendixObject;

public class CHK_JAVA_SAMPLE extends CustomJavaAction<java.lang.String>
{
	private IMendixObject __Parameter;
	private myfirstmodule.proxies.TicketComment Parameter;

	public CHK_JAVA_SAMPLE(IContext context, IMendixObject Parameter)
	{
		super(context);
		this.__Parameter = Parameter;
	}

	@java.lang.Override
	public java.lang.String executeAction() throws Exception
	{
		this.Parameter = this.__Parameter == null ? null : myfirstmodule.proxies.TicketComment.initialize(getContext(), __Parameter);

		// BEGIN USER CODE
		DataValidationInfo info = new DataValidationInfo(Parameter.getMendixObject().getId().toLong());
		info.addErrorField("contents", "サンプルエラー");
		addDataValidationFeedback(info);
//		throw new com.mendix.systemwideinterfaces.MendixRuntimeException("Java action was not implemented");
		return "hello";
		// END USER CODE
	}

	/**
	 * Returns a string representation of this action
	 * @return a string representation of this action
	 */
	@java.lang.Override
	public java.lang.String toString()
	{
		return "CHK_JAVA_SAMPLE";
	}

	// BEGIN EXTRA CODE
	// END EXTRA CODE
}
